apiVersion: v1
kind: Service
metadata:
  name: biomaj-prometheus
spec:
  selector:
    app: biomaj-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prom-server
    - protocol: TCP
      port: 9093
      targetPort: 9093
      name: alert-manager
