apiVersion: v1
kind: Pod
metadata:
  name: biomaj-mongo
  labels:
      app: biomaj-mongo
spec:
  containers:
  - name: biomaj-mongo
    image: mongo
    volumeMounts:
      - mountPath: /data/db
        name: biomaj-mongodb
  volumes:
    - name: biomaj-mongodb
      persistentVolumeClaim:
        claimName: biomaj-mongodb-pv-claim