apiVersion: v1
kind: Pod
metadata:
  name: biomaj-influxdb
  labels:
      app: biomaj-influxdb
spec:
  containers:
  - name: biomaj-influxdb
    image: influxdb
    env:
      - INFLUXDB_DB=biomaj
      - INFLUXDB_USER=biomaj
      - INFLUXDB_PASSWORD=biomaj

    volumeMounts:
      - mountPath: /var/lib/influxdb
        name: biomaj-influxdb
  volumes:
    - name: biomaj-influxdb
      persistentVolumeClaim:
        claimName: biomaj-influxdb-pv-claim