apiVersion: v1
kind: Service
metadata:
  name: biomaj-traefik
spec:
  type: NodePort
  selector:
    app: biomaj-traefik
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui
