apiVersion: v1
kind: Pod
metadata:
  name: biomaj-redis
  labels:
      app: biomaj-redis
spec:
  containers:
  - name: biomaj-redis
    image: redis
    volumeMounts:
      - mountPath: /data
        name: biomaj-redis
  volumes:
    - name: biomaj-redis
      persistentVolumeClaim:
        claimName: biomaj-redis-pv-claim