sudo: required

services:
  - docker

before_install:
  - echo "BIOMAJ_DIR=$(pwd)" > .env
  - echo "BIOMAJ_DATA_DIR=$(pwd)/biomaj" >> .env
  - mkdir -p biomaj biomaj/conf biomaj/log biomaj/lock biomaj/db biomaj/process biomaj/cache

script:
  - docker run --rm -i hadolint/hadolint < Dockerfile || true
  - docker-compose config --q
  - docker-compose build
  - docker-compose up -d
  - docker-test.sh
  - docker-compose down
