 version: '2'

 services:
    biomaj-mongo:
        image: mongo
        volumes:
            - ${BIOMAJ_DIR}/mongo:/data/db

    biomaj-redis:
        image: redis
        volumes:
            - ${BIOMAJ_DIR}/redis:/data

    biomaj-elasticsearch:
        image: elasticsearch

    biomaj-rabbitmq:
        image: rabbitmq
        hostname: biomaj-rabbitmq
        volumes:
            - ${BIOMAJ_DIR}/rabbitmq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=biomaj
            - RABBITMQ_DEFAULT_PASS=biomaj

    biomaj-consul:
        image: progrium/consul
        hostname: consulnode1
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:53"
        command: ["-server", "-bootstrap", "-ui-dir", "/ui"]

    biomaj-prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ${BIOMAJ_DIR}/biomaj-config/prometheus.yml:/etc/prometheus/prometheus.yml
        depends_on:
            - biomaj-consul
        command:
            - '-storage.local.retention=720h'
            - '-config.file=/etc/prometheus/prometheus.yml'

    biomaj-internal-proxy:
        image: osallou/biomaj-proxy
        # To be deleted in production
        ports:
            - "5080:80"
        volumes:
            - ${BIOMAJ_DIR}/proxy/internal:/proxy:ro
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj
        depends_on:
            - biomaj-consul

    biomaj-public-proxy:
        image: osallou/biomaj-proxy
        volumes:
            - ${BIOMAJ_DIR}/proxy/public:/proxy:ro
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        ports:
            - "5000:80"
        depends_on:
            - biomaj-consul

    biomaj-user-web:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajuser
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
        command: ["gunicorn", "-b", "0.0.0.0:5000", "--capture-output", "--error-logfile", "/var/log/biomaj-web.log", "biomaj_user.wsgi:app"]


    biomaj-download-web:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajdownload
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
        command: ["gunicorn", "-b", "0.0.0.0:5000", "--capture-output", "--error-logfile", "/var/log/biomaj-web.log", "biomaj_download.biomaj_download_web:app"]


    biomaj-download-message:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajdownload
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
        command: ["python3", "/root/biomaj-download/bin/biomaj_download_consumer.py"]

    biomaj-process-web:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajprocess
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
        command: ["gunicorn", "-b", "0.0.0.0:5000", "--capture-output", "--error-logfile", "/var/log/biomaj-web.log", "biomaj_process.biomaj_process_web:app"]


    biomaj-process-message:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajprocess
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
        command: ["python3", "/root/biomaj-process/bin/biomaj_process_consumer.py"]

    biomaj-daemon-web:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajdaemon
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
            - biomaj-user-web
            - biomaj-download-web
            - biomaj-process-web
        command: ["gunicorn", "-b", "0.0.0.0:5000", "--capture-output", "--error-logfile", "/var/log/biomaj-web.log", "biomaj_daemon.daemon.biomaj_daemon_web:app"]

    biomaj-daemon-message:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_USER_PASSWORD=${BIOMAJ_USER_PASSWORD}
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
            - REDIS_PREFIX=biomajdaemon
            - RABBITMQ_USER=biomaj
            - RABBITMQ_PASSWORD=biomaj
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
            - biomaj-elasticsearch
            - biomaj-user-web
            - biomaj-download-web
            - biomaj-process-web
        command: ["python3", "/root/biomaj-daemon/bin/biomaj_daemon_consumer.py"]

    biomaj-watcher-web:
        image: osallou/biomaj-test
        volumes:
            - ${BIOMAJ_DIR}/biomaj:/var/lib/biomaj/data
        environment:
            - BIOMAJ_CONFIG=/etc/biomaj/config.yml
        depends_on:
            - biomaj-mongo
            - biomaj-consul
            - biomaj-rabbitmq
            - biomaj-redis
            - biomaj-user-web
            - biomaj-daemon-web
        command: ["/root/watcher.sh"]
