 version: '2'

 services:

    biomaj-zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"

    graylog-mongo:
        image: "mongo:3"

    graylog-elasticsearch:
        image: "elasticsearch:2"
        command: "elasticsearch -Des.cluster.name='graylog'"

    graylog:
        image: graylog2/server:2.1.1-1
        environment:
            GRAYLOG_PASSWORD_SECRET: somepasswordpepper
            GRAYLOG_ROOT_PASSWORD_SHA2: 415e8a6ba1c3eb93e81df34731acc3d60efee685c8e6f7412592a45ba3a0e3b0
            GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
        links:
            - graylog-mongo:mongo
            - graylog-elasticsearch:elasticsearch
        ports:
            - "9000:9000"
