apiVersion: v1
kind: PersistentVolume
metadata:
  name: biomaj-banks-pv-volume
  labels:
    biomaj: banks
spec:
  capacity:
    storage: {{.Values.banksPvCapacity}}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{.Values.banksPvPath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - slave0
